# Use postgres/example user/password credentials
version: '3.1'

services:

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: example
      POSTGRES_DB: deposit_tvs_DB
    ports:
      - "3333:5432"
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080